Develop holdemclub start
JJ81/HC-Mobile pull request #1
Opened 2017-02-16 03:41 UTC by JJ81

test to create pull request

2017-02-17 04:46 UTC, Parkseokje reviewed
좋아요ㅋ

2017-02-17 04:47 UTC, Parkseokje requested changes
Approve 테스트

2017-02-17 04:47 UTC, Parkseokje approved these changes

2017-02-17 06:32 UTC, merged

2017-02-19 00:51 UTC, JJ81 commented on .eslintrc.js
> +    // "indent": [
이와 같이 코딩 컨벤션을 위한 설정을 해제하면 차후에 문제가 될 수 있으니
lint에 대한 주석을 해제하고 코딩 컨벤션을 최대한 따르는 것이 
협업에 좋을 듯합니다.
이의가 있거나 문제가 될 경우 발언을 해야 합니다.